name = "PolicyGradientExamples"
uuid = "0bcf1857-5341-4ac2-afa9-fde77acb150e"
authors = ["Jamie Mair <jamie.mair@nottingham.ac.uk> and contributors"]
version = "0.1.0"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ReinforcementLearning = "158674fc-8238-5cab-b5ba-03dfc80d1318"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
